
create table CUSTOMERS
(
    id int generated by default as identity ,
    name varchar(255)  not null ,
    surname varchar(255)   not null  ,
    age int  not null check (age>0)  ,
    phone_number bigint
);

create table ORDERS
(
    id           serial primary key ,
    date         date default current_date,
    customer_id  int references customers(id),
    product_name varchar(255) not null ,
    amount       int not null check (amount>=0)

);

select product_name from orders JOIN customers ON customers.id = orders.customer_id
where upper(customers.name) = upper('alexey');